# Generated by Django 3.0.2 on 2020-02-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='boy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, default='images/def.jpg', null=True, upload_to='images/')),
                ('nick_name', models.CharField(max_length=20)),
                ('character', models.TextField(max_length=50)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
